build: off

clone_folder: c:\gopath\src\github.com\go-python\gpython

branches:
  only:
    - master

environment:
  GOPATH: c:\gopath
  PATH: '%GOPATH%\bin;%PATH%;C:\msys64\mingw64\bin'
  matrix:
    - TARGET: x86_64-pc-windows-gnu

stack: go 1.13

build_script:
  - go get -v -t -race ./...

test_script:
  - go test -race ./...
